<?php

function search($search, $attribute) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER
        );
        if ("all" == $attribute){
            $select_query = "SELECT * FROM website NATURAL JOIN user NATURAL JOIN account
                             WHERE website_id LIKE \"%{$search}%\" OR website_name LIKE \"%{$search}%\"
                             OR website_url LIKE \"%{search}%\" OR user_id LIKE \"%{search}%\"
                             OR first_name LIKE \"%{search}%\" OR last_name LIKE \"%{search}%\"
                             OR email LIKE \"%{search}%\" OR account_id LIKE \"%{search}%\"
                             OR username LIKE \"%{search}%\" OR password LIKE \"%{search}%\"
                             OR creation_time LIKE \"%{search}%\" OR comment LIKE \"%{search}%\"";
            $statement = $db -> prepare($select_query);
            $statement -> execute();
        }else{
            $select_query = "SELECT * FROM website NATURAL JOIN user NATURAL JOIN account
                             WHERE {$attribute} LIKE \"%{$search}%\"";
            $statement = $db -> prepare($select_query);
            $statement -> execute();
        }

        if (count($statement -> fetchAll()) == 0) {
            return 0;
        } else {
            echo "      <table>\n";
            echo "        <thead>\n";
            echo "          <tr>\n";
            echo "            <th>Account ID</th>\n";
            echo "            <th>Website ID</th>\n";
            echo "            <th>User ID</th>\n";
            echo "            <th>Website Name</th>\n";
            echo "            <th>Website URL</th>\n";
            echo "            <th>First Name</th>\n";
            echo "            <th>Last Name </th>\n";
            echo "            <th>Email</th>\n";
            echo "            <th>Username</th>\n";
            echo "            <th>Password</th>\n";
            echo "            <th>Creation Time</th>\n";
            echo "            <th>Comment</th>\n";
            echo "          </tr>\n";
            echo "        </thead>\n";
            echo "        <tbody>\n";

            // Populate the table with data coming from the database...
            foreach ($db ->query($select_query) as $row) {
                echo "          <tr>\n";
                echo "            <td>" . htmlspecialchars($row[7]) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row[0]) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row[1]) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row[2]) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row[3]) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row[4]) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row[5]) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row[6]) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row[8]) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row[9]) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row[10]) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row[11]) . "</td>\n";
                echo "          </tr>\n";
            }

            echo "         </tbody>\n";
            echo "      </table>\n";
        }
    } catch( PDOException $e ) {
        echo '<p>The following message was generated by function <code>search</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";
        echo "<p>There are a few reasons for this. Perhaps the database doesn’t exist or wasn’t mounted. Does the volume/drive containing the database have read and write permissions?</p>\n";
        echo '<p>Click <a href="./">here</a> to go back.</p>';

        exit;
    }
}
